@gameboard=[["","",""],["","",""],["","",""]]
@rows=["A","B","C"]
@current_player="x"
@continue=true

puts"Hey"

defprint_game_board
puts" 1 2 3 "
@gameboard.each_with_indexdo|row,i|
puts"#{@rows[i]}#{row.join("|")}"
puts" ---------"if@gameboard.count-1!=i
end
end

defplayer(symbol)
not_valid=true
whilenot_valid
puts"Player'#{symbol}',wherewouldyouliketoplay?"
position=gets.chomp
ifposition.length==2
if@rows.include?(position[0].to_s.upcase)&&(1..3).to_a.include?(position[1].to_i)
row=@rows.index(position[0].to_s.upcase)
column=position[1].to_i-1
spot=@gameboard[row][column]
ifspot==""
#placeit
@gameboard[row][column]=symbol
not_valid=false
if@current_player=="x"
@current_player="o"
else
@current_player="x"
end
else
puts"seatstaken"
end
else
puts"notavalidspot"
end
else
puts"toomanyortoofewcharacters!expecting2"
end
end
end

defcheck_if_game_over
#checkforthreeinarowandsetcurrentplayer
winner_found=false
winner=nil
#horizontal
@gameboard.eachdo|row|
ifrow==["x","x","x"]||row==["o","o","o"]
winner_found=true
ifrow[0]=="x"
winner="x"
elsifrow[1]=="o"
winner="o"
end
end
end
#vertical
if[@gameboard[0][0],@gameboard[1][0],@gameboard[2][0]]==["x","x","x"]||[@gameboard[0][0],@gameboard[1][0],@gameboard[2][0]]==["o","o","o"]
winner_found=true
if@gameboard[0][0]=="x"
winner="x"
elsif@gameboard[0][0]=="o"
winner="o"
end
elsif[@gameboard[0][1],@gameboard[1][1],@gameboard[2][1]]==["x","x","x"]||[@gameboard[0][1],@gameboard[1][1],@gameboard[2][1]]==["o","o","o"]
winner_found=true
if@gameboard[0][1]=="x"
winner="x"
elsif@gameboard[0][1]=="o"
winner="o"
end
elsif[@gameboard[0][2],@gameboard[1][2],@gameboard[2][2]]==["x","x","x"]||[@gameboard[0][2],@gameboard[1][2],@gameboard[2][2]]==["o","o","o"]
winner_found=true
if@gameboard[0][2]=="x"
winner="x"
elsif@gameboard[0][2]=="o"
winner="o"
end
end
#diagnal
if[@gameboard[0][0],@gameboard[1][1],@gameboard[2][2]]==["x","x","x"]||[@gameboard[0][0],@gameboard[1][1],@gameboard[2][2]]==["o","o","o"]
winner_found=true
if@gameboard[0][0]=="x"
winner="x"
elsif@gameboard[0][0]=="o"
winner="o"
end
elsif[@gameboard[0][2],@gameboard[1][1],@gameboard[2][0]]==["x","x","x"]||[@gameboard[0][2],@gameboard[1][1],@gameboard[2][0]]==["o","o","o"]
winner_found=true
if@gameboard[0][2]=="x"
winner="x"
elsif@gameboard[0][2]=="o"
winner="o"
end
end
ifwinner_found
puts"#{winner}wins!"
@continue=false
end

cat_counter=0
@gameboard.eachdo|row|
row.eachdo|spot|
cat_counter+=1ifspot=="x"||spot=="o"
end
end

ifcat_counter==9
puts"CatsGame!"
@continue=false
end
end

while@continue
print_game_board
player(@current_player)
check_if_game_over
end
